/**
 * Director Mode — Keyframe Analyzer (Vision Model)
 * Issue #243: Analyzes extracted keyframe JPEGs using a vision-capable LLM
 * to produce rich scene descriptions for intelligent editing decisions.
 *
 * Design:
 *   - Batches ALL keyframe images into a single LLM request to minimise
 *     premium model usage (1 request instead of N).
 *   - Selects a representative subset when too many keyframes exist.
 *   - Populates the KeyframeInfo.description field in-place.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { logger } from "../../logging/logger.js";
import type { KeyframeInfo } from "./types.js";
import type { CopilotWrapper } from "../../copilot/copilot-wrapper.js";
import type { SdkAttachment } from "../../copilot/copilot-wrapper.js";

/**
 * Prompt for batched vision analysis — instructs the LLM to describe ALL
 * attached frames in one structured response keyed by filename.
 */
function buildBatchVisionPrompt(frameLabels: string[]): string {
  const listing = frameLabels.map((l, i) => `  ${i + 1}. ${l}`).join("\n");
  return `You are a professional video editor reviewing ${frameLabels.length} keyframe images from a video.

For EACH attached image, write a 1-2 sentence description.

Focus on:
- Who/what is visible (people, objects, text on screen, graphics)
- Framing and composition (close-up, wide shot, over-the-shoulder, etc.)
- Implied motion or action
- Lighting, mood, and dominant colors

Be specific, factual, and use professional film/video terminology.

FORMAT: Respond with EXACTLY one line per image, prefixed by its number.
Do NOT add any preamble, headers, or extra text.

Images (in order):
${listing}

EXAMPLE OUTPUT (for 3 images):
1. Medium shot of a speaker at a podium with warm stage lighting and a blue backdrop.
2. Close-up product shot on a white surface, soft diffused lighting from the left.
3. Wide establishing shot of a modern office space with natural window light.

Now describe all ${frameLabels.length} images:`;
}

/** Single-image fallback prompt (used when batching fails or for 1 frame). */
const SINGLE_FRAME_PROMPT = `Describe this video frame in 1-2 concise sentences for a professional video editor.

Focus on:
- Who/what is visible (people, objects, text on screen, graphics)
- Framing and composition (close-up, wide shot, over-the-shoulder, etc.)
- Implied motion or action
- Lighting, mood, and dominant colors

Be specific, factual, and use professional film/video terminology.
Do NOT speculate about context outside the visible frame.
Do NOT include any preamble — start directly with the description.`;

/** Maximum keyframes to analyze by default (controls cost/time). */
const DEFAULT_MAX_KEYFRAMES = 30;

export interface KeyframeAnalysisOptions {
  /** Maximum number of keyframes to analyze (default: 30) */
  maxKeyframes?: number;
  /** @deprecated — no longer used; kept for API compat. */
  delayMs?: number;
  /** Model to use for vision analysis (default: system default) */
  model?: string;
  /** Progress callback: (analyzed, total, currentDescription) */
  onProgress?: (analyzed: number, total: number, lastDescription?: string) => void;
}

/**
 * Check whether a description was generated by scene detection metadata
 * (i.e., NOT a rich vision-model description).
 */
function isGenericDescription(description?: string): boolean {
  if (!description) return true;
  return (
    description.startsWith("Major visual transition") ||
    description.startsWith("Scene change") ||
    description.startsWith("Visual sample at")
  );
}

/**
 * Analyze keyframe images using a vision-capable LLM.
 *
 * Sends ALL images in a **single batched request** to minimise premium model
 * usage. Falls back to individual calls only if the batch response fails to
 * parse.
 *
 * Mutates the KeyframeInfo.description field in-place with rich descriptions.
 */
export async function analyzeKeyframes(
  keyframes: KeyframeInfo[],
  copilot: CopilotWrapper,
  options: KeyframeAnalysisOptions = {},
): Promise<{ analyzed: number; skipped: number; failed: number }> {
  const {
    maxKeyframes = DEFAULT_MAX_KEYFRAMES,
    model,
    onProgress,
  } = options;

  // Select a representative subset if there are too many keyframes
  const toAnalyze = selectRepresentativeKeyframes(keyframes, maxKeyframes);
  const total = toAnalyze.length;

  logger.info(
    `[KeyframeAnalyzer] Starting vision analysis: ${total} of ${keyframes.length} keyframes (batched)`,
  );

  // ── Partition into "needs analysis" vs "already done / missing" ──────
  const needsAnalysis: { index: number; kf: KeyframeInfo }[] = [];
  let skipped = 0;

  for (let i = 0; i < toAnalyze.length; i++) {
    const kf = toAnalyze[i];

    if (!isGenericDescription(kf.description)) {
      skipped++;
      onProgress?.(skipped + needsAnalysis.length, total, kf.description);
      continue;
    }

    // Verify file exists
    try {
      await fs.access(kf.framePath);
    } catch {
      logger.warn(`[KeyframeAnalyzer] Frame file not found, skipping: ${kf.framePath}`);
      skipped++;
      onProgress?.(skipped + needsAnalysis.length, total);
      continue;
    }

    needsAnalysis.push({ index: i, kf });
  }

  if (needsAnalysis.length === 0) {
    logger.info("[KeyframeAnalyzer] All keyframes already described, nothing to do.");
    return { analyzed: 0, skipped, failed: 0 };
  }

  // ── Batch request — single LLM call for all images ───────────────────
  let failed = 0;
  let analyzed = 0;

  try {
    const descriptions = await describeBatch(
      copilot,
      needsAnalysis.map((n) => n.kf),
      model,
    );

    for (let i = 0; i < needsAnalysis.length; i++) {
      const { kf } = needsAnalysis[i];
      const desc = descriptions[i];
      if (desc) {
        kf.description = desc;
        analyzed++;
        logger.debug(
          `[KeyframeAnalyzer] Keyframe (${kf.timestamp.toFixed(1)}s): ${desc.slice(0, 80)}…`,
        );
      } else {
        failed++;
        logger.warn(`[KeyframeAnalyzer] No description parsed for keyframe at ${kf.timestamp.toFixed(1)}s`);
      }
      onProgress?.(skipped + i + 1, total, kf.description);
    }
  } catch (error) {
    // Batch failed entirely — fall back to individual calls
    const msg = error instanceof Error ? error.message : String(error);
    logger.warn(`[KeyframeAnalyzer] Batch vision call failed (${msg}), falling back to individual calls`);

    for (let i = 0; i < needsAnalysis.length; i++) {
      const { kf } = needsAnalysis[i];
      try {
        const desc = await describeKeyframe(copilot, kf.framePath, model);
        if (desc) {
          kf.description = desc;
          analyzed++;
        } else {
          failed++;
        }
      } catch (err) {
        failed++;
        const errMsg = err instanceof Error ? err.message : String(err);
        logger.warn(`[KeyframeAnalyzer] Individual fallback failed at ${kf.timestamp.toFixed(1)}s: ${errMsg}`);
      }
      onProgress?.(skipped + i + 1, total, kf.description);
    }
  }

  logger.info(
    `[KeyframeAnalyzer] Vision analysis complete: ` +
    `${analyzed} described, ${skipped} skipped, ${failed} failed ` +
    `(${total} total, 1 batched LLM request)`,
  );

  return { analyzed, skipped, failed };
}

/**
 * Send ALL keyframe images in a single batched LLM request.
 * Returns an array of descriptions aligned 1:1 with the input keyframes.
 * Missing/unparsed entries are returned as empty strings.
 */
async function describeBatch(
  copilot: CopilotWrapper,
  keyframes: KeyframeInfo[],
  model?: string,
): Promise<string[]> {
  // Build attachments and labels for the prompt
  const attachments: SdkAttachment[] = [];
  const labels: string[] = [];

  for (const kf of keyframes) {
    const basename = path.basename(kf.framePath);
    const label = `${basename} (${kf.timestamp.toFixed(1)}s)`;
    labels.push(label);
    attachments.push({ type: "file", path: kf.framePath, displayName: label });
  }

  const prompt = buildBatchVisionPrompt(labels);

  logger.info(
    `[KeyframeAnalyzer] Sending batched vision request with ${keyframes.length} images`,
  );

  const chunks: string[] = [];
  const stream = copilot.chat(prompt, {
    tools: [],
    attachments,
    ...(model ? { model } : {}),
  });

  for await (const chunk of stream) {
    chunks.push(chunk);
  }

  const raw = chunks.join("").trim();

  // Parse numbered responses: "1. description\n2. description\n..."
  return parseBatchResponse(raw, keyframes.length);
}

/**
 * Parse a numbered-list response from the batch vision call.
 * Returns an array of descriptions, one per keyframe.
 * Handles various formats: "1. desc", "1: desc", "1 - desc", etc.
 */
function parseBatchResponse(raw: string, expectedCount: number): string[] {
  const results: string[] = new Array(expectedCount).fill("");

  // Split by numbered prefixes: "1. " or "1: " or "1 - " etc.
  const linePattern = /^(\d+)[.):\-]\s*/;
  const lines = raw.split("\n");

  let currentIndex = -1;
  let currentParts: string[] = [];

  const flush = () => {
    if (currentIndex >= 0 && currentIndex < expectedCount) {
      results[currentIndex] = currentParts.join(" ").trim();
    }
    currentParts = [];
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const match = trimmed.match(linePattern);
    if (match) {
      flush();
      currentIndex = parseInt(match[1], 10) - 1; // 1-based → 0-based
      currentParts.push(trimmed.replace(linePattern, ""));
    } else if (currentIndex >= 0) {
      // Continuation line for the current description
      currentParts.push(trimmed);
    }
  }
  flush();

  return results;
}

/**
 * Fallback: send a single keyframe image to the vision model.
 * Used only when the batched call fails entirely.
 */
async function describeKeyframe(
  copilot: CopilotWrapper,
  framePath: string,
  model?: string,
): Promise<string> {
  const chunks: string[] = [];
  const stream = copilot.chat(SINGLE_FRAME_PROMPT, {
    tools: [],
    attachments: [{ type: "file", path: framePath }],
    ...(model ? { model } : {}),
  });

  for await (const chunk of stream) {
    chunks.push(chunk);
  }

  return chunks.join("").trim();
}

/**
 * Select a representative subset of keyframes for analysis.
 *
 * Strategy:
 *   - 60% of slots go to the highest-confidence scene changes (most important transitions)
 *   - 40% of slots go to evenly-spaced temporal samples from the remaining keyframes
 *   - Final result is sorted chronologically
 *
 * This ensures both the most visually significant moments AND even temporal
 * coverage are captured, giving the LLM the best possible context.
 */
function selectRepresentativeKeyframes(
  keyframes: KeyframeInfo[],
  maxCount: number,
): KeyframeInfo[] {
  if (keyframes.length <= maxCount) return keyframes;

  // Sort by scene score descending
  const sorted = [...keyframes].sort((a, b) => b.sceneScore - a.sceneScore);

  // Take top 60% by scene score
  const highScoreCount = Math.floor(maxCount * 0.6);
  const highScore = sorted.slice(0, highScoreCount);
  const highScoreSet = new Set(highScore);

  // Remaining keyframes (not already selected)
  const remaining = keyframes.filter((kf) => !highScoreSet.has(kf));

  // Fill remaining 40% with evenly spaced temporal samples
  const temporalSlots = maxCount - highScore.length;
  const temporal: KeyframeInfo[] = [];
  if (remaining.length > 0 && temporalSlots > 0) {
    const step = Math.max(1, Math.floor(remaining.length / temporalSlots));
    for (let i = 0; i < remaining.length && temporal.length < temporalSlots; i += step) {
      temporal.push(remaining[i]);
    }
  }

  // Combine and sort chronologically
  return [...highScore, ...temporal].sort((a, b) => a.timestamp - b.timestamp);
}
