/**
 * Director Mode — Keyframe Analyzer (Vision Model)
 * Issue #243: Analyzes extracted keyframe JPEGs using a vision-capable LLM
 * to produce rich scene descriptions for intelligent editing decisions.
 *
 * Design:
 *   - Processes keyframes sequentially to avoid rate limiting.
 *   - Configurable delay between API calls (default 2s).
 *   - Selects a representative subset when too many keyframes exist.
 *   - Populates the KeyframeInfo.description field in-place.
 */

import fs from "node:fs/promises";
import { logger } from "../../logging/logger.js";
import type { KeyframeInfo } from "./types.js";
import type { CopilotWrapper } from "../../copilot/copilot-wrapper.js";

const KEYFRAME_VISION_PROMPT = `Describe this video frame in 1-2 concise sentences for a professional video editor.

Focus on:
- Who/what is visible (people, objects, text on screen, graphics)
- Framing and composition (close-up, wide shot, over-the-shoulder, etc.)
- Implied motion or action
- Lighting, mood, and dominant colors

Be specific, factual, and use professional film/video terminology.
Do NOT speculate about context outside the visible frame.
Do NOT include any preamble — start directly with the description.`;

/** Maximum keyframes to analyze by default (controls cost/time). */
const DEFAULT_MAX_KEYFRAMES = 30;

/** Default delay between vision API calls in milliseconds. */
const DEFAULT_DELAY_MS = 2000;

export interface KeyframeAnalysisOptions {
  /** Maximum number of keyframes to analyze (default: 30) */
  maxKeyframes?: number;
  /** Delay in ms between API calls to avoid rate limiting (default: 2000) */
  delayMs?: number;
  /** Model to use for vision analysis (default: system default) */
  model?: string;
  /** Progress callback: (analyzed, total, currentDescription) */
  onProgress?: (analyzed: number, total: number, lastDescription?: string) => void;
}

const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

/**
 * Check whether a description was generated by scene detection metadata
 * (i.e., NOT a rich vision-model description).
 */
function isGenericDescription(description?: string): boolean {
  if (!description) return true;
  return (
    description.startsWith("Major visual transition") ||
    description.startsWith("Scene change") ||
    description.startsWith("Visual sample at")
  );
}

/**
 * Analyze keyframe images using a vision-capable LLM.
 * Mutates the KeyframeInfo.description field in-place with rich descriptions.
 *
 * @param keyframes - All keyframes from a clip (or merged across clips)
 * @param copilot - CopilotWrapper instance for LLM calls
 * @param options - Configuration for rate limiting, batch size, progress
 */
export async function analyzeKeyframes(
  keyframes: KeyframeInfo[],
  copilot: CopilotWrapper,
  options: KeyframeAnalysisOptions = {},
): Promise<{ analyzed: number; skipped: number; failed: number }> {
  const {
    maxKeyframes = DEFAULT_MAX_KEYFRAMES,
    delayMs = DEFAULT_DELAY_MS,
    model,
    onProgress,
  } = options;

  // Select a representative subset if there are too many keyframes
  const toAnalyze = selectRepresentativeKeyframes(keyframes, maxKeyframes);
  const total = toAnalyze.length;

  logger.info(
    `[KeyframeAnalyzer] Starting vision analysis: ${total} of ${keyframes.length} keyframes ` +
    `(delay: ${delayMs}ms between calls)`,
  );

  let analyzed = 0;
  let skipped = 0;
  let failed = 0;

  for (let i = 0; i < toAnalyze.length; i++) {
    const kf = toAnalyze[i];

    // Skip keyframes that already have rich (non-generic) descriptions
    if (!isGenericDescription(kf.description)) {
      skipped++;
      analyzed++;
      onProgress?.(analyzed, total, kf.description);
      continue;
    }

    // Verify the frame file exists on disk
    try {
      await fs.access(kf.framePath);
    } catch {
      logger.warn(`[KeyframeAnalyzer] Frame file not found, skipping: ${kf.framePath}`);
      skipped++;
      analyzed++;
      onProgress?.(analyzed, total);
      continue;
    }

    // Call the vision model
    try {
      const description = await describeKeyframe(copilot, kf.framePath, model);
      if (description) {
        kf.description = description;
        logger.debug(
          `[KeyframeAnalyzer] Keyframe ${i + 1}/${total} (${kf.timestamp.toFixed(1)}s): ${description.slice(0, 80)}…`,
        );
      } else {
        failed++;
        logger.warn(`[KeyframeAnalyzer] Empty description for keyframe at ${kf.timestamp.toFixed(1)}s`);
      }
    } catch (error) {
      failed++;
      const msg = error instanceof Error ? error.message : String(error);
      logger.warn(`[KeyframeAnalyzer] Failed to analyze keyframe at ${kf.timestamp.toFixed(1)}s: ${msg}`);
    }

    analyzed++;
    onProgress?.(analyzed, total, kf.description);

    // Rate-limit: wait between calls (skip delay after the last one)
    if (i < toAnalyze.length - 1) {
      await sleep(delayMs);
    }
  }

  logger.info(
    `[KeyframeAnalyzer] Vision analysis complete: ` +
    `${analyzed - skipped - failed} described, ${skipped} skipped, ${failed} failed ` +
    `(${total} total)`,
  );

  return { analyzed: analyzed - skipped - failed, skipped, failed };
}

/**
 * Send a single keyframe image to the vision model for description.
 */
async function describeKeyframe(
  copilot: CopilotWrapper,
  framePath: string,
  model?: string,
): Promise<string> {
  const chunks: string[] = [];
  const stream = copilot.chat(KEYFRAME_VISION_PROMPT, {
    tools: [],
    attachments: [{ type: "file", path: framePath }],
    ...(model ? { model } : {}),
  });

  for await (const chunk of stream) {
    chunks.push(chunk);
  }

  return chunks.join("").trim();
}

/**
 * Select a representative subset of keyframes for analysis.
 *
 * Strategy:
 *   - 60% of slots go to the highest-confidence scene changes (most important transitions)
 *   - 40% of slots go to evenly-spaced temporal samples from the remaining keyframes
 *   - Final result is sorted chronologically
 *
 * This ensures both the most visually significant moments AND even temporal
 * coverage are captured, giving the LLM the best possible context.
 */
function selectRepresentativeKeyframes(
  keyframes: KeyframeInfo[],
  maxCount: number,
): KeyframeInfo[] {
  if (keyframes.length <= maxCount) return keyframes;

  // Sort by scene score descending
  const sorted = [...keyframes].sort((a, b) => b.sceneScore - a.sceneScore);

  // Take top 60% by scene score
  const highScoreCount = Math.floor(maxCount * 0.6);
  const highScore = sorted.slice(0, highScoreCount);
  const highScoreSet = new Set(highScore);

  // Remaining keyframes (not already selected)
  const remaining = keyframes.filter((kf) => !highScoreSet.has(kf));

  // Fill remaining 40% with evenly spaced temporal samples
  const temporalSlots = maxCount - highScore.length;
  const temporal: KeyframeInfo[] = [];
  if (remaining.length > 0 && temporalSlots > 0) {
    const step = Math.max(1, Math.floor(remaining.length / temporalSlots));
    for (let i = 0; i < remaining.length && temporal.length < temporalSlots; i += step) {
      temporal.push(remaining[i]);
    }
  }

  // Combine and sort chronologically
  return [...highScore, ...temporal].sort((a, b) => a.timestamp - b.timestamp);
}
